### ISSUE TITLE
ValueError: masked arrays are not supported

### ISSUE THREAD

**Issue by GuidoDavoli** [csyhuang/hn2016_falwa#27]
Hi Claire,
I successfully run your example "demo_script_for_nh2018" (I copied the code from the Jupiter notebook in a .py file and I run the code on my machine). However, when I try to use the same code with my data (model output interpolated to a regular lat/lon grid) I got the following error:

```
Dimension of time: 124
Traceback (most recent call last):

  File "<ipython-input-1-26269db047c2>", line 1, in <module>
    runfile('/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/examples/nh2018_science/demo_script_for_nh2018_GUIDO.py', wdir='/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/examples/nh2018_science')

  File "/home/guido/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/examples/nh2018_science/demo_script_for_nh2018_GUIDO.py", line 159, in <module>
    interpolated_theta[tstep, :, :, :], static_stability = qgfield_object.interpolate_fields()

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 401, in interpolate_fields
    print(isinstance(self.qgpv,np.ma.MaskedArray))

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 695, in qgpv
    variable=self._qgpv, interp_axis=1, northern_hemisphere_results_only=False)

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 284, in _return_interp_variables
    return self._interp_back(variable, self.ylat, self.ylat_no_equator, which_axis=interp_axis)

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 257, in _interp_back
    )(interp_to)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/_lib/_util.py", line 237, in _asarray_validated
    raise ValueError('masked arrays are not supported')

ValueError: masked arrays are not supported

```

The problem seems to be related with the **qgfield_object.qgpv** variable. In fact, I got the same error when I try to directly access to this variable:

```

qgfield_object.qgpv

Traceback (most recent call last):

  File "<ipython-input-9-57090d46ce92>", line 1, in <module>
    qgfield_object.qgpv

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 695, in qgpv
    variable=self._qgpv, interp_axis=1, northern_hemisphere_results_only=False)

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 284, in _return_interp_variables
    return self._interp_back(variable, self.ylat, self.ylat_no_equator, which_axis=interp_axis)

  File "/mnt/6d042d15-9e3c-4da4-b065-f073e9857fcb/Dropbox/python/LWA/hn2016_falwa/hn2016_falwa/oopinterface.py", line 257, in _interp_back
    )(interp_to)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)

  File "/home/guido/anaconda3/lib/python3.7/site-packages/scipy/_lib/_util.py", line 237, in _asarray_validated
    raise ValueError('masked arrays are not supported')

ValueError: masked arrays are not supported


```

Have you any idea on how to solve the issue? My date are apparently ok, without missing values, and I prepared them mimicking the structure of the example data.
Thank you!

**Comment by GuidoDavoli** [comment]
And the problem seems to be ultimately related to the scipy.interpolate.interp1d function, which does not support masked data. However, I do not understand when/where the data masking happens.

**Comment by csyhuang** [comment]
Hi Guido,

The data in your netCDF file is stored in masked array format. It seems that ECMWF is using masked array in some recent updates so not only you encounter this problem. Here is the quick fix:

When you are passing the masked array into the `QGField`, add `.data` in the input variable, such as `ylat.data` - this convert the masked array `ylat` to a normal array `ylat.data` which can be processed by the `QGField` object.

Please let me know whether you have fixed the issue this way.

Thanks,

Clare

**Comment by csyhuang** [comment]
I will do a minor release adding a function to convert masked array into array before doing the interpolation, such that users don't have to worry about conversion when passing data into `QGField`. I will keep your ticket active until the release is done.

Thanks!

**Comment by csyhuang** [comment]
Hi @GuidoDavoli , I just added procedures to handle masked array. Please pull the changes I made onto your master branch and rerun your code (you don't have to add `.data` in that case) - see if it works?

**Comment by GuidoDavoli** [comment]
Hi Claire, thank you for your updates. Unfortunately, your changes to the code does not solve my problem. The error message is still the same. 
Running the new version of the code I do not receive the warning messages you implemented in oopinterface.py (lines 91-109), so the problem should not be in the input files.
Using the np.ma.is_masked() function I did many checks in the code and I do not find anything masked. In particular, all the variables passed to interp1d (inside the _interp_back function, oopinterface.py, line 285) are not masked, but interp1d fails generating the error I reported.

**Comment by csyhuang** [comment]
Hi @GuidoDavoli , that is unexpected. I probably have to try running your script such that I can produce your error and debug it. Would you mind emailing me one timestep of data (U, V, T) and your full script so that I can run it on my side?
