### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Veenarinesingh** [csyhuang/hn2016_falwa#59]
Hi Clare,

After typing
python setup.py  develop
The error message shows:

Couldn't find index page for 'pytest-runner' (maybe misspelled?)
No local packages or download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    zip_safe=False
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/core.py", line 186, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/numpy_distribution.py", line 14, in __init__
    Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

V

**Comment by csyhuang** [comment]
Hi Vershan,

It looks like you are still using python 2.7 (but it is no longer maintained) - can you try creating a new environment with python 3 (with pytest runner installed) and try again?

I found a thread online related to that (but the author was already using python 3.x):
https://stackoverflow.com/questions/50691479/error-could-not-find-suitable-distribution-for-requirement-parsepytest-runner

Let me know if that works. Thanks!

Clare

**Comment by csyhuang** [comment]
I added python 2.7 into the test workflow. It actually passes. So the support for the package itself has no issue:
https://github.com/csyhuang/hn2016_falwa/actions/runs/3697731332/jobs/6263075398

**Comment by Veenarinesingh** [comment]
Solved
